import type { ChatMessage } from "../storage/types";
import type {
  AgentAdapter,
  AgentEnv,
  AgentResponse,
  BinaryAsset,
  SandboxCommand,
  SandboxFile,
} from "./types";

const ZEROCLAW_BIN_PATH = "/tmp/zeroclaw";

export const zeroclawAdapter: AgentAdapter = {
  id: "zeroclaw",
  name: "ZeroClaw",

  generateConfig(_env: AgentEnv, _history?: ChatMessage[]): SandboxFile[] {
    // Config is generated by `zeroclaw onboard` in installCommands instead
    return [];
  },

  buildCommand(message: string, history?: ChatMessage[]): SandboxCommand {
    let prompt = message;
    if (history && history.length > 0) {
      const historyText = history
        .map((m) => `${m.role === "user" ? "User" : "Assistant"}: ${m.content}`)
        .join("\n");
      prompt = `[Conversation history]\n${historyText}\n\n[New message]\n${message}`;
    }
    return {
      cmd: ZEROCLAW_BIN_PATH,
      args: ["agent", "-m", prompt],
      env: { HOME: "/tmp" },
    };
  },

  parseResponse(
    stdout: string,
    stderr: string,
    exitCode: number,
  ): AgentResponse {
    if (exitCode !== 0) {
      const errorDetail = stderr.trim() || stdout.trim() || "Unknown error";
      return {
        success: false,
        message: "The agent encountered an error.",
        error: errorDetail,
      };
    }

    const text = stdout.trim();
    if (!text) {
      return {
        success: true,
        message: "The agent completed but produced no output.",
      };
    }

    return { success: true, message: text };
  },

  binaryAssets(): BinaryAsset[] {
    return [
      {
        localPath: "public/bin/zeroclaw-linux-amd64",
        sandboxPath: ZEROCLAW_BIN_PATH,
      },
    ];
  },

  installCommands(): SandboxCommand[] {
    return [
      {
        cmd: "chmod",
        args: ["+x", ZEROCLAW_BIN_PATH],
      },
    ];
  },

  /**
   * Run `zeroclaw onboard` to generate a valid config with all required fields.
   * This avoids hand-crafting TOML that breaks when the schema changes.
   */
  onboardCommand(env: AgentEnv): SandboxCommand {
    const providerMap: Record<string, string> = {
      anthropic: "anthropic",
      openai: "openai",
      openrouter: "openrouter",
    };
    const provider = providerMap[env.llmProvider] ?? env.llmProvider;

    return {
      cmd: ZEROCLAW_BIN_PATH,
      args: [
        "onboard",
        "--api-key", env.llmApiKey,
        "--provider", provider,
        "--memory", "none",
      ],
      env: { HOME: "/tmp" },
    };
  },
};
