import type {
  AgentAdapter,
  AgentEnv,
  AgentResponse,
  BinaryAsset,
  SandboxCommand,
  SandboxFile,
} from "./types.js";
import type { ChatMessage } from "../types.js";
import { buildAgentCommand, buildOnboardCommand } from "../command-builder.js";
import { parseOutput } from "../output-parser.js";
import { getBinaryPath } from "../binary.js";

const ZEROCLAW_BIN_PATH = "/tmp/zeroclaw";

export const zeroclawAdapter: AgentAdapter = {
  id: "zeroclaw",
  name: "ZeroClaw",

  generateConfig(_env: AgentEnv, _history?: ChatMessage[]): SandboxFile[] {
    // Config is generated by `zeroclaw onboard` instead
    return [];
  },

  buildCommand(message: string, history?: ChatMessage[]): SandboxCommand {
    return buildAgentCommand(ZEROCLAW_BIN_PATH, message, history);
  },

  parseResponse(stdout: string, stderr: string, exitCode: number): AgentResponse {
    const result = parseOutput(stdout, stderr, exitCode);
    return {
      success: result.success,
      message: result.message,
      error: result.error,
    };
  },

  binaryAssets(): BinaryAsset[] {
    const localPath = getBinaryPath("linux-x64");
    return [
      {
        localPath: localPath ?? "public/bin/zeroclaw-linux-amd64",
        sandboxPath: ZEROCLAW_BIN_PATH,
      },
    ];
  },

  installCommands(): SandboxCommand[] {
    return [
      {
        cmd: "chmod",
        args: ["+x", ZEROCLAW_BIN_PATH],
      },
    ];
  },

  onboardCommand(env: AgentEnv): SandboxCommand {
    return buildOnboardCommand(ZEROCLAW_BIN_PATH, {
      provider: env.llmProvider,
      apiKey: env.llmApiKey,
      model: env.llmModel,
      memory: "none",
    });
  },
};
