import { randomUUID } from "node:crypto";
import { input, password, select } from "@inquirer/prompts";
import chalk from "chalk";
import type { Preset } from "../presets/types.js";

const MODEL_DEFAULTS: Record<string, string> = {
  anthropic: "claude-sonnet-4-20250514",
  openai: "gpt-4o",
  openrouter: "anthropic/claude-sonnet-4-20250514",
};

function isSensitive(key: string): boolean {
  const lower = key.toLowerCase();
  return lower.includes("key") || lower.includes("token") || lower.includes("secret");
}

export async function collectEnvVars(
  preset: Preset,
  useDefaults: boolean
): Promise<Record<string, string>> {
  const env: Record<string, string> = {};

  console.log(chalk.cyan("\nConfiguring environment variables:\n"));

  for (const envVar of preset.envVars) {
    // Auto-generate if specified and not requiring user input
    if (envVar.autoGenerate === "uuid") {
      const value = randomUUID();
      env[envVar.key] = value;
      console.log(chalk.dim(`  ${envVar.key} = <auto-generated>`));
      continue;
    }

    // Check if already set in process env
    const existing = process.env[envVar.key];
    if (existing) {
      env[envVar.key] = existing;
      console.log(chalk.dim(`  ${envVar.key} = <from environment>`));
      continue;
    }

    // Resolve dynamic defaults (e.g., LLM_MODEL depends on LLM_PROVIDER)
    let defaultValue = envVar.default;
    if (envVar.key === "CLOUDCLAW_LLM_MODEL" && env["CLOUDCLAW_LLM_PROVIDER"]) {
      defaultValue = MODEL_DEFAULTS[env["CLOUDCLAW_LLM_PROVIDER"]] ?? defaultValue;
    }

    // Use defaults in --yes mode
    if (useDefaults) {
      if (defaultValue) {
        env[envVar.key] = defaultValue;
        console.log(chalk.dim(`  ${envVar.key} = ${defaultValue}`));
        continue;
      }
      if (envVar.required) {
        console.error(
          chalk.red(`  Missing required variable: ${envVar.key}`)
        );
        console.error(
          chalk.red(`  Set ${envVar.key} in your environment or run without --yes`)
        );
        process.exit(1);
      }
      continue;
    }

    // Interactive prompts
    let value: string;

    if (envVar.choices) {
      value = await select({
        message: envVar.prompt,
        choices: envVar.choices.map((c) => ({ name: c, value: c })),
        default: defaultValue,
      });
    } else if (isSensitive(envVar.key)) {
      value = await password({
        message: envVar.prompt,
        mask: "*",
      });
    } else {
      value = await input({
        message: envVar.prompt,
        default: defaultValue,
      });
    }

    if (!value && envVar.required) {
      console.error(chalk.red(`  ${envVar.key} is required.`));
      process.exit(1);
    }

    env[envVar.key] = value;
  }

  return env;
}
