import { getAllAdapters } from "./registry.js";

/**
 * Extract channel-related env vars from a parsed agent config object.
 *
 * Iterates over all registered wake hook adapters, checks if the agent has
 * that channel configured, and maps the agent's config fields to CloudClaw
 * env var names.
 *
 * Generated secrets (webhook verification tokens) are NOT extracted here —
 * they're generated by the CLI's secrets system and mapped separately.
 */
export function extractChannelEnvVars(
  agentConfig: Record<string, unknown>,
  channelsConfigKey: string,
): Record<string, string> {
  const channelsConfig = agentConfig[channelsConfigKey] as
    | Record<string, Record<string, unknown>>
    | undefined;
  if (!channelsConfig) return {};

  const vars: Record<string, string> = {};

  for (const adapter of getAllAdapters()) {
    const mapping = adapter.envMapping;
    const channelCfg = channelsConfig[mapping.configKey];
    if (!channelCfg) continue;

    for (const field of mapping.fields) {
      const value = channelCfg[field.configField];
      if (typeof value === "string" && value) {
        vars[field.envVar] = value;
      }
    }
  }

  return vars;
}

/**
 * Get all generated secret env var names across all adapters.
 *
 * Used by the CLI to know which per-channel secrets to generate.
 * Returns entries like: { envVar: "CLOUDCLAW_TELEGRAM_WEBHOOK_SECRET", purpose: "..." }
 */
export function getChannelSecretDefinitions(): Array<{
  channelId: string;
  envVar: string;
  purpose: string;
}> {
  const defs: Array<{ channelId: string; envVar: string; purpose: string }> = [];

  for (const adapter of getAllAdapters()) {
    for (const secret of adapter.envMapping.generatedSecrets) {
      defs.push({
        channelId: adapter.channelId,
        envVar: secret.envVar,
        purpose: secret.purpose,
      });
    }
  }

  return defs;
}
