#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
NPM_DIR="$SCRIPT_DIR/npm"

# ============================================================
# Phase 1: Linux targets (Docker)
# ============================================================

echo "=========================================="
echo "  Phase 1: Linux targets (Docker)"
echo "=========================================="

# Prepare build context
CONTEXT_DIR=$(mktemp -d)
trap "rm -rf $CONTEXT_DIR" EXIT

cp -r /tmp/zeroclaw-patch "$CONTEXT_DIR/zeroclaw-patch"
mkdir -p "$CONTEXT_DIR/packages"
cp -r "$SCRIPT_DIR" "$CONTEXT_DIR/packages/zeroclaw-napi"
cp "$SCRIPT_DIR/Dockerfile" "$CONTEXT_DIR/Dockerfile"

LINUX_TARGETS=(
  "aarch64-unknown-linux-gnu:linux-arm64-gnu"
  "x86_64-unknown-linux-gnu:linux-x64-gnu"
)

for entry in "${LINUX_TARGETS[@]}"; do
  RUST_TARGET="${entry%%:*}"
  NPM_SUBDIR="${entry##*:}"
  IMAGE_TAG="zeroclaw-napi-${NPM_SUBDIR}"
  CONTAINER_NAME="zeroclaw-napi-build-${NPM_SUBDIR}"

  echo ""
  echo "--- Building $RUST_TARGET ---"

  docker build \
    --build-arg TARGET="$RUST_TARGET" \
    -t "$IMAGE_TAG" \
    "$CONTEXT_DIR"

  # Extract the .node artifact
  docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
  docker create --name "$CONTAINER_NAME" "$IMAGE_TAG"

  # Find the .node file (napi names it based on target)
  NODE_FILE=$(docker run --rm "$IMAGE_TAG" sh -c 'ls /app/*.node 2>/dev/null' | head -1)
  if [ -z "$NODE_FILE" ]; then
    echo "ERROR: No .node file found for $RUST_TARGET"
    docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
    exit 1
  fi

  NODE_BASENAME=$(basename "$NODE_FILE")
  echo "  Found: $NODE_BASENAME"

  mkdir -p "$NPM_DIR/$NPM_SUBDIR"
  docker cp "$CONTAINER_NAME:$NODE_FILE" "$NPM_DIR/$NPM_SUBDIR/$NODE_BASENAME"

  # Also grab index.js and index.d.ts (generated by napi, same for all targets)
  docker cp "$CONTAINER_NAME:/app/index.js" "$SCRIPT_DIR/index.js" 2>/dev/null || true
  docker cp "$CONTAINER_NAME:/app/index.d.ts" "$SCRIPT_DIR/index.d.ts" 2>/dev/null || true

  docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

  echo "  Copied to npm/$NPM_SUBDIR/$NODE_BASENAME"
done

# ============================================================
# Phase 2: macOS targets (native on host)
# ============================================================

echo ""
echo "=========================================="
echo "  Phase 2: macOS targets (native on host)"
echo "=========================================="

# Source cargo env if not in PATH yet
if ! command -v cargo &>/dev/null && [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

if [ "$(uname -s)" != "Darwin" ]; then
  echo "  Skipping macOS builds (not on macOS)"
elif ! command -v cargo &>/dev/null; then
  echo "  WARNING: cargo not found. Skipping macOS builds."
  echo "  Install Rust via: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
else
  # The Cargo.toml references zeroclaw at path = "/zeroclaw-patch".
  # For native macOS builds, temporarily patch it to use /tmp/zeroclaw-patch.
  CARGO_TOML="$SCRIPT_DIR/Cargo.toml"
  cp "$CARGO_TOML" "$CARGO_TOML.bak"
  if [ -d /tmp/zeroclaw-patch ] && [ ! -e /zeroclaw-patch ]; then
    echo "  Patching Cargo.toml to use /tmp/zeroclaw-patch"
    sed -i '' 's|path = "/zeroclaw-patch"|path = "/tmp/zeroclaw-patch"|' "$CARGO_TOML"
  fi
  trap 'mv "$CARGO_TOML.bak" "$CARGO_TOML" 2>/dev/null; rm -rf $CONTEXT_DIR' EXIT

  MACOS_TARGETS=(
    "aarch64-apple-darwin:darwin-arm64"
    "x86_64-apple-darwin:darwin-x64"
  )

  for entry in "${MACOS_TARGETS[@]}"; do
    RUST_TARGET="${entry%%:*}"
    NPM_SUBDIR="${entry##*:}"

    echo ""
    echo "--- Building $RUST_TARGET ---"

    # Ensure the target is installed
    rustup target add "$RUST_TARGET" 2>/dev/null || true

    # Build using napi CLI from the package directory
    cd "$SCRIPT_DIR"
    npx napi build --release --platform --target "$RUST_TARGET"

    # Move the .node file to the correct npm subdir
    NODE_FILE=$(ls "$SCRIPT_DIR"/zeroclaw-napi.*.node 2>/dev/null | grep "$NPM_SUBDIR" | head -1)
    if [ -z "$NODE_FILE" ]; then
      echo "  ERROR: No .node file found for $RUST_TARGET"
      exit 1
    fi

    NODE_BASENAME=$(basename "$NODE_FILE")
    mkdir -p "$NPM_DIR/$NPM_SUBDIR"
    mv "$NODE_FILE" "$NPM_DIR/$NPM_SUBDIR/$NODE_BASENAME"
    echo "  Moved to npm/$NPM_SUBDIR/$NODE_BASENAME"
  done

  cd "$REPO_ROOT"
fi

# ============================================================
# Phase 3: Finalize
# ============================================================

echo ""
echo "=========================================="
echo "  Phase 3: Finalize"
echo "=========================================="

# Re-link workspace packages
echo "  Running pnpm install..."
cd "$REPO_ROOT"
pnpm install 2>/dev/null || true

# Summary
echo ""
echo "=== Build Summary ==="
echo ""
for dir in "$NPM_DIR"/*/; do
  subdir=$(basename "$dir")
  node_file=$(ls "$dir"/*.node 2>/dev/null | head -1)
  if [ -n "$node_file" ]; then
    size=$(ls -lh "$node_file" | awk '{print $5}')
    echo "  $subdir: $(basename "$node_file") ($size)"
  else
    echo "  $subdir: NOT BUILT"
  fi
done

echo ""
if [ -f "$SCRIPT_DIR/index.js" ]; then
  echo "  index.js: OK"
else
  echo "  index.js: MISSING"
fi
if [ -f "$SCRIPT_DIR/index.d.ts" ]; then
  echo "  index.d.ts: OK"
else
  echo "  index.d.ts: MISSING"
fi

echo ""
echo "Done! Test with:"
echo "  node -e \"import('zeroclaw-napi').then(m => console.log('Providers:', m.getProviders().length))\""
