/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getChannelSchema(key: string): string | null

export declare function getChannelsSchema(): string

export declare function getDefaultConfigJson(): string

export declare function getMemoryBackends(): Array<JsMemoryBackend>

export declare function getProviders(): Array<JsProviderInfo>

export declare function getSavedConfig(): Promise<string>

export interface JsMemoryBackend {
  key: string
  label: string
}

export interface JsProviderInfo {
  name: string
  displayName: string
  local: boolean
}

export interface JsProviderSetupResult {
  provider: string
  apiKey: string
  model: string
  apiUrl?: string
}

export interface JsValidationResult {
  ok: boolean
  channel: string
  message: string
}

export declare function runChannelWizard(): Promise<string>

export declare function runProviderWizard(): Promise<JsProviderSetupResult>

export declare function validateChannel(key: string, configJson: string): Promise<JsValidationResult>
